[project]
name = "ancestry-data-backend"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "duckdb==1.2.2",
    "geopy==2.4.1",
    "pandas>=3.0.2",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pylint>=4.0.5",
    "taskipy>=1.14.1",
]

[tool.ruff]
indent-width = 2

[tool.taskipy.tasks]
test =  "python -m unittest tests/*.py"
lint = "ruff format src tests --config pyproject.toml"
build_data = "python src/preprocess.py"
build_db = "python src/db_load.py"
