name: main
run-name: ${{ github.actor }}
on: [push]

jobs:
  lint-and-test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.7"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run linting
        run: uv run task lint

      - name: Try installing duckpgq from community
        run: |
          uv run python -c "
          import duckdb

          con = duckdb.connect(config={"allow_unsigned_extensions": "true"})
          print('DuckDB version:', duckdb.__version__)

          con.install_extension('duckpgq', repository='community')
          con.load_extension('duckpgq')

          result = con.sql(\"SELECT 'duckpgq loaded ok'\").fetchone()
          print(result[0])
          "

      - name: Preprocess sample data
        run: uv run task build_sample_data

      - name: Build sample DB
        run: uv run task build_sample_db

      - name: Run tests
        run: uv run task test